### ISSUE TITLE
Unexpected duplicate "margin"

### ISSUE THREAD

**Issue by dextel2** [dextel2/core-server#18]
public/css/cart.css

```css
.cart__item-list {
list-style: none;
margin: 0;
padding: 0;
margin: auto;

}
```

``` css
.cart__item h1,
 .cart__item h2 {
margin-right: 1rem;
font-size: 1.2rem;
margin: 0;
 }

```
